# Generated by Django 2.0 on 2019-07-07 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsimage',
            old_name='image',
            new_name='image_url',
        ),
    ]
