# Generated by Django 2.0 on 2019-07-07 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20190707_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsimage',
            old_name='image_url',
            new_name='image',
        ),
    ]
